prioritize = ["nvim", "tmux"]

[nvim]
class = "terminal.nvim"
cmd = "xterm -class ${app_class} -e nvim"

[tmux]
class = "terminal.tmux"
cmd = "xterm -class ${app_class} -e tmux"

[chrome]
class = "Google-chrome"
cmd = "google-chrome-stable"

[firefox]
class = "firefox"
cmd = "firefox"

[zen-browser]
class = "zen"
cmd = "zen"
