[prioritize]
apps = ["nvim", "tmux"]
position = "right"

[app.nvim]
class = "terminal.nvim"
cmd = "xterm -class ${app_class} -e nvim"

[app.tmux]
class = "terminal.tmux"
cmd = "xterm -class ${app_class} -e tmux"

[app.chrome]
class = "Google-chrome"
cmd = "google-chrome-stable"

[app.firefox]
class = "firefox"
cmd = "firefox"

[app.zen-browser]
class = "zen"
cmd = "zen"
